addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - gfortran-5
cache: packages
sudo: false
latex: false
language: r
r:
- release
#- devel
install:
- mkdir -p ~/.R && cp ./util/gcc5.conf ~/.R/Makevars
- R --no-save -f ./util/update-dependencies.R
script: ./util/travis/script
env:
- OMP_NUM_THREADS=2 IMX_SAFE=1
