os:
- linux
addons:
  ssh_known_hosts: openmx.psyc.virginia.edu
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - gfortran-5
matrix:
  include:
  - os: osx
    osx_image: xcode7.3
    env:
    - MODE=build
dist: trusty
sudo: false
cache: packages
latex: true
language: r
install:
- mkdir -p ~/.R
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp ./util/gcc5.conf ~/.R/Makevars; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./util/travis/install-macos; fi
- R --no-save -f ./util/update-dependencies.R --args ./DESCRIPTION.in
script: "./util/travis/script"
env:
  matrix:
  - MODE=test IMX_OPT_ENGINE=NPSOL
  - MODE=test IMX_OPT_ENGINE=CSOLNP
  - MODE=test IMX_OPT_ENGINE=SLSQP
#  - MODE=cran-check  # blocked on roxygen2 bug
branches:
  except:
  - stable   # already tested
before_deploy:
- openssl aes-256-cbc -K $encrypted_8548c8dde734_key -iv $encrypted_8548c8dde734_iv -in util/travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ./util/travis/deploy
  on: osx
