os: linux
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - gfortran-5
cache:
- packages
sudo: false
latex: false
language: r
r:
- release
#- devel
install:
- mkdir -p ~/.R && cp ./util/gcc5.conf ~/.R/Makevars
- R --no-save -f ./util/update-dependencies.R --args ./DESCRIPTION.in
script: ./util/travis/script
after_success: ./util/travis/nightly-success
env:
- OMP_NUM_THREADS=2 IMX_SAFE=1 IMX_OPT_ENGINE=NPSOL
- OMP_NUM_THREADS=2 IMX_SAFE=1 IMX_OPT_ENGINE=CSOLNP
- OMP_NUM_THREADS=2 IMX_SAFE=1 IMX_OPT_ENGINE=SLSQP
branches:
  except:
  - stable   # already tested
